Nawaranga/Controllers/GuestsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nawaranga.Data;
using Nawaranga.Data.Services;
using Nawaranga.Data.Static;
using Nawaranga.Models;
using System.Data;

namespace Nawaranga.Controllers
{
    public class GuestsController : Controller
    {
        private readonly IGuestsService _context;

        public GuestsController(IGuestsService context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.GetAllAsync();

            return View(data);
        }

       
        public async Task<IActionResult> Details(int id)
        {
            var guestDetails = await _context.GetByIdAsync(id);

            if (guestDetails == null)
            {
                return View("NotFound");
            }

            return View(guestDetails);
        }

        [Authorize(Roles = UserRoles.Admin)]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = UserRoles.Admin)]
        [HttpPost]

        public async Task<IActionResult> Create(Guest guest)
        {
            if (!ModelState.IsValid)
            {
                return View(guest);
            }

            await _context.AddAsync(guest);

            return RedirectToAction(nameof(Index));

        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {

            var guestDetails = await _context.GetByIdAsync(id);

            if (guestDetails == null)
            {
                return View("NotFound");
            }

            return View(guestDetails);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Guest guest)
        {
            if (!ModelState.IsValid)
            {
                return View(guest);
            }

            await _context.UpdateAsync(id, guest);

            return RedirectToAction(nameof(Index));

        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {

            var guestDetails = await _context.GetByIdAsync(id);

            if (guestDetails == null)
            {
                return View("NotFound");
            }

            return View(guestDetails);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guestDetails = await _context.GetByIdAsync(id);

            if (guestDetails == null)
            {
                return View("NotFound");
            }

            await _context.DeleteAsync(id);

            return RedirectToAction(nameof(Index));

        }
    }
}

Nawaranga/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nawaranga.Data;
using Nawaranga.Data.Services;
using Nawaranga.Models;

namespace Nawaranga.Controllers
{
    public class RoomsController : Controller
    {
        private readonly IRoomsService _context;

        public RoomsController(IRoomsService context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.GetAllAsync();

            return View(data);
        }

        public async Task<IActionResult> Filter(string searchString)
        {
            var data = await _context.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var result = data.Where(n => n.Description.Contains(searchString)).ToList();
                return View("Index", result);
            }
            return View("Index", data);


        }


        [Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]

        public async Task<IActionResult> Create(Room room)
        {
            if(!ModelState.IsValid)
            {
               return View(room);
            }

           await _context.AddAsync(room);

            return RedirectToAction(nameof(Index));

        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int id)
        {
            var roomDetails = await _context.GetByIdAsync(id);

            if(roomDetails==null)
            {
                return View("NotFound");
            }

            return View(roomDetails);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {

            var roomDetails = await _context.GetByIdAsync(id);

            if (roomDetails == null)
            {
                return View("NotFound");
            }

            return View(roomDetails);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]

        public async Task<IActionResult> Edit(int id,Room room)
        {
            if (!ModelState.IsValid)
            {
                return View(room);
            }

            await _context.UpdateAsync(id,room);

            return RedirectToAction(nameof(Index));

        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {

            var roomDetails = await _context.GetByIdAsync(id);

            if (roomDetails == null)
            {
                return View("NotFound");
            }

            return View(roomDetails);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var roomDetails = await _context.GetByIdAsync(id);

            if (roomDetails == null)
            {
                return View("NotFound");
            }

            await _context.DeleteAsync(id);

            return RedirectToAction(nameof(Index));

        }

        
    }
}

Nawaranga/Controllers/StaffsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Nawaranga.Data;
using Nawaranga.Data.Services;
using Nawaranga.Models;
using System.Data;

namespace Nawaranga.Controllers
{
    public class StaffsController : Controller
    {
        private readonly IStaffsService _context;

        public StaffsController(IStaffsService context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _context.GetAllAsync();

            return View(data);
        }

        public async Task<IActionResult> Details(int id)
        {
            var staffDetails = await _context.GetByIdAsync(id);

            if (staffDetails == null)
            {
                return View("NotFound");
            }

            return View(staffDetails);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]

        public async Task<IActionResult> Create(Staff staff)
        {
            if (!ModelState.IsValid)
            {
                return View(staff);
            }

            await _context.AddAsync(staff);

            return RedirectToAction(nameof(Index));

        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {

            var staffDetails = await _context.GetByIdAsync(id);

            if (staffDetails == null)
            {
                return View("NotFound");
            }

            return View(staffDetails);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]

        public async Task<IActionResult> Edit(int id, Staff staff)
        {
            if (!ModelState.IsValid)
            {
                return View(staff);
            }

            await _context.UpdateAsync(id, staff);

            return RedirectToAction(nameof(Index));

        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {

            var staffDetails = await _context.GetByIdAsync(id);

            if (staffDetails == null)
            {
                return View("NotFound");
            }

            return View(staffDetails);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staffDetails = await _context.GetByIdAsync(id);

            if (staffDetails == null)
            {
                return View("NotFound");
            }

            await _context.DeleteAsync(id);

            return RedirectToAction(nameof(Index));

        }
    }
}

Nawaranga/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">Not Found!!! Please enter valid information.</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Rooms" asp-action="Index">Home Page</a>
    </div>
</div>

Nawaranga/Views/Shared/_CreateItem.cshtml
@model string;
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 35px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Add New
        </a>
    </div>
}

Nawaranga/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

    @if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}
    

else{


    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User) </button>
        <ul class="dropdown-menu dropdown-menu" aria-labelledby="profile-btn">
            
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="bi bi-people"></i>Users
                </a>
            </li>
            }
            <li>
                <form asp-controller="Account" asp-action="Logout">
                    <button class="dropdown-item">
                        <i class="bi bi-box-arrow-in-right"></i> Log Out
                    </button>
                </form>
            </li>
        </ul>
    </div>
    @*User profile section*@
    @*<div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
            aria-expanded="false">
            <i class="bi bi-person-badge"></i> Hello @UserManager.GetUserName(User)
        </button>
        
            @if (User.IsInRole("Admin"))
            {
                
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                        <i class="bi bi-people"></i> Users
                    </a>
                
            }
        
    </div>
    <span style = "padding:0px 5px" ></span >
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
*@
}

Nawaranga/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nawaranga</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nawaranga.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Rooms" asp-action="Index">Nawaranga</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="badge-info bi-gear"></i> Management
                            </a>



                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Guests" asp-action="Index"><i class="bi bi-person-circle"></i> Guests</a>
                                    <a class="dropdown-item" asp-controller="Rooms" asp-action="Index"><i class='fab fa-buromobelexperte'></i>Rooms</a>
                                    <a class="dropdown-item" asp-controller="Staffs" asp-action="Index"><i class="bi bi-person-bounding-box"></i>Staffs</a>
                                </div>
                                </li>
                            }
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-controller="Rooms" asp-action="Filter" style="display:flex" style="padding-right: 20px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a room..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                    <span style="padding:0px 5px"></span>
                    <partial name="_Identity.cshtml" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>